### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by cxorm** [sysprog21/cserv#1]
IMHO the [introduction of `cserv`](https://github.com/sysprog21/cserv#cserv) has a typo in following description : 
It ideally has one worker process per cpu or processor core, and each one is capable of handling `thounds` of incoming network connections per worker. 

It should be 
It ideally has one worker process per cpu or processor core, and each one is capable of handling `thousands` of incoming network connections per worker.

**Comment by jserv** [comment]
Thank @cxorm for pointing that out. Please send the relevant pull request.
